### ISSUE TITLE
Browser only?

### ISSUE THREAD

**Issue by flockonus** [azer/play-audio#1]
Hi, I come here from https://npmjs.org/package/alert

can you please specify it is browser only since npm is primarily for node?

this is what happens when I try invoking from node.js

```
> require('alert')
ReferenceError: document is not defined
    at play (/Users/flockonus/node_modules/alert/node_modules/play-audio/lib/player.js:10:18)
    at Object.<anonymous> (/Users/flockonus/node_modules/alert/index.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
```

**Comment by azer** [comment]
Hmm, I've been planning to add NodeJS support for a while but didn't have time yet.

**Comment by flockonus** [comment]
It would be awesome indeed! Few packages support client and server =)

**Comment by parthasharathi** [comment]
i am getting error like.
  dom || ( dom = document.documentElement );
                 ^
ReferenceError: document is not defined
